sudo: false
language: java
install:
- mvn -s .settings.xml install -q -U -DskipTests=true -Dmaven.test.redirectTestOutputToFile=true
script:
- mvn -s .settings.xml $MVN_GOAL -nsu -Dmaven.test.redirectTestOutputToFile=true
jdk:
- oraclejdk8
env:
  global:
  - FEATURE_BRANCH=$(echo ${TRAVIS_BRANCH} | grep "^.*/.*$" && echo true || echo false)
  - INTERNAL_BUILD=$(echo ${TRAVIS_REPO_SLUG} | grep -q "^SMARTRACTECHNOLOGY/.*$"
    && echo true || echo false)
  - MVN_GOAL=$([ "${TRAVIS_PULL_REQUEST}" == "false" -a "${TRAVIS_TAG}" == "" -a "${FEATURE_BRANCH}"
    == "false" -a "${INTERNAL_BUILD}" == "true" ] && echo deploy || echo install)
  - VERSION=$(mvn validate | grep Building | head -1 | sed -e 's/.* //')
  - secure: Xx8Z8UaS+n2JwJe4U87rCrCC+RVCOjPNUs+lDGOEY+TKwfKAzPw1j1TMteBBdzqDsNIq7MupZO8oGn1B18Gbv338mYd/uSK5RK0wk73eBM7409hlAaperOrRpKxf/iINrknvZUB5k/NNXJmCbJDkOrIfJScXEvZabHFpE53fd53dsZ0JZuKx9v7VtjV0pPy6cOFsH7c+RXv+OF9KLXDCRhIqn75BOJHXwzP2PnpF3Z3i8OdHANWKqgimhE+NI/HoOKrMhg3MxRuV6YaSX2x4cb3MqRSCwdRakyS+JPwY91erlfuO4Tkit3FvCL1JioNkE2dgLcue2X+7VIuWB5Py7Rzw/C3bsj3MFsmfwNIORUACkeuB+lHgd8U4/chXobFjhxyqwOLes1JkrNCYjHFaNrwqtOgLighfb9UksyhTpfVcfhP3ExTjLk5MZjLvEHjrka8aNJadfQqotLGFvkgVCAEtzKo7QjYGCOgsC9hMVl30gBMnXLWx43S+XpOwuPNBD3NXEhLWlBmKk/wRh3tNPLHYlH25GGEo/0xRBA2o3G417o3HPqt7gI4pFo9vkfK+bz7fnQsuamf08zxSQErp2uF4+0zVnsLLBWuLqggp+MVHD7mqqOts90ryoINfOa72jPvydZxxT6rNLEUTV3F8tp7J3Cafe3sM76gQUzvQ8Zo=
  - secure: MDYXU7UPkhOGQWVxxcRb7x+u1atYHxHgXMzmzFvWIF0udew9+qV1eC2tiJTPA+n31hmlS2SqlHM8ZbX1oomm67vu/1wA1FCw6r/YAeqahRhRvS5Vs0G101mkTzK6zPrWkMoTDyAN3CS2OuL1d2FGWon4RrewdxZMrhQKibMV+p/Pxi5+QeFN0i0zkCh1LclKfsGQYBPkJcd0CAzupG9MJPmJ4GXjouTjUK1AQFsUzm7WLOaBYxEGXtNByjzDjwGpmMrwNOpjtD2VB2tPxg3LAhdN0Z6+dOyh4dvf23t/JdTHVmzkbgeue4DeVIEwlRlZILdaVypCG2ZdkypdAsvkQkmSXlvMrVInc/Z05IFLYzMIjGYOoJes3Qr5LF4TIBRQdneMkU5Oowg02TwhX2+IftEfTdSONuBJf2hdPIVsQT/LrDvmJPvJ/VyOZayMd4zdLQrqq9Zd+0Zt5fx2NMI1PlqQvSDGYxYu96zA7dETXFN8D9VOXLQAtF0u13SVUzZSLP9Mtin3kwTlnQEILrTM8UJQ1bEMelyGx58lCUI3V6WgmZKsE0oJ9nntAH6OyniB/6Xp3Zo4xbq8u63gylYD3JsedcK0xbXgjtRrm0NE2/5usCsErC9bcFO/WC0MYU0tyRnh2mofIvByrP1Jpqgr05frBFI9bklPNPytSB2YK8c=
notifications:
  slack:
    on_success: change
    rooms:
      secure: igEFwk1oG08e0+5UvsPhUKQSOT/aHYYMg7v8UPUpBzp8Dlv+/USE/i+HITy5iJTLRoP/mvjTqwJhpa0m311ngdVM+/STrVepvk3XfuzcdhGaO8dSngNsAStS/2LDQRzj8bNCbPhGydbzeY72cuzmxRukamWI/YEoZbC1ttGqo60DTYOqm8TnXBHKiek7lT1orHGCSozMGGYoRY3GiYj/pTHW7P/+kFYCi2km7AuDuT0yqqgK6zWd3B2Fdng4bmpnd/Zuw6IYv6w85pOeQL9zDGET+M5tycoNZ3PYFDLbbIGiz31z1+c8yJN9N6ilGIXUwlL8OBljQpWRFSXbFaeM5wu/i/h3oixu0zz579/YuaTaYVr0fF94+D3P0anyyzhlU8gT2snsmTNZSdKPaXCEFQ9ffWETrJWds8bIwKeqrm7fdkWOCbPdMQBSOPR5R9Dswmhu6eNgbUA2YkAUQiQoCc1ESp1IsWFqa07jLqQAdUzfomvUD9SpyAlspjbX0OGnCakcxh0a9gMmMVbApZwIzi9mEh6xhhZZZVwF6rsLcSaJyFNcsSYGl7xt3A941N4QNxVXyswwvUWFtQxbS9dZKoveffgaP1B44JEypfuZs9eXEwOagMLKNjXkNY0HKK0nsjCJ8YGBlvXEe5Kn4yFC9gUre+r0RO67hFVB1FnJiTE=
