server:
  port: 0

flyway:
  enabled: true

spring:
  datasource:
    #
    # CREATE DATABASE objects;  GRANT ALL PRIVILEGES ON objects.* TO 'cosmos'@'localhost' IDENTIFIED BY 'dev';  FLUSH PRIVILEGES;
    #
    name: objects
    hostname: localhost
    url: jdbc:mysql://${spring.datasource.hostname}/${spring.datasource.name}?autoReconnect=true
    username: cosmos
    password: dev
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
      naming_strategy: org.hibernate.cfg.EJB3NamingStrategy
